name: CD

on:
  push:
    branches: [master]

jobs:
  deploy_github_pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "17"
          cache: "npm"
      - run: npm ci
      - run: npm run build
      - uses: crazy-max/ghaction-github-pages@v2.5.0
        with:
          build_dir: dist/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
